### ISSUE TITLE
Getting: "The state token is invalid or has expired. Please try again." - no call of authCallback

### ISSUE THREAD

**Issue by russenreaktor** [googlesamples/apps-script-oauth1#2]
I am setting the callback function like in README.md
  
var service = OAuth1.createService('meh');
  ...
service.setCallbackFunction('authCallback');

I am jumping to "usercallback" Url where I am getting "The state token is invalid or has expired. Please try again.".

I am expecting that authCallback function will be called but its not the case.

Script is running under Googel for Works

https://script.google.com/a/macros/fancy-domain.org/d/ProjectId/usercallback?state=ADEpC8ytq-GO0eq0qvx-Uvv3IEPOBqwCN9DuPpyll_y0fPRnxgkx-kJwoszp8mvsiN_16JlL27bWc1I22xoielBWXqRNK0yywlsTtOzyAEIJHMlfA3sZpftblybm8Craztn3LSMxuybH9Sq68qCxouyb8PAojn5OnM2ygJf&oauth_token=b4f5a69611fb5c9083e9a3040089e92e&oauth_verifier=d30ea54d161ce0d8ed49ee52e6736225

**Comment by jptrsn** [comment]
Make sure you've put the project key into the related field. I got this error after making a copy of my script, when the key changed.

**Comment by printminion** [comment]
The problem kinda solved... ...my OAuth-Server expected the callback URLs to be not longer than 255 chars. It means it cut the state parameter short and made the stateToken invalid.

**Comment by vsuthar** [comment]
@printminion, could you please share what did you do to solve this issue? I am facing similar issue with OAuth2 where because of the longer state token, my OAuth server starts throwing error it couldn't persist the request entity. When I give smaller token(i.e. manually edited which is not correct), OAuth server doesn't throw any error and correctly redirects to the redirect uri but because the state token isn't correct it fails at final redirection.

**Comment by printminion** [comment]
@vsuthar Just check how your OAuth-Server is saving the callback URLs. 
In my case, my DB had only 255 chars reserved in the table for callback URLs.. ..it means callback URLs were just corrupted.
I extended it to 512 chars and everything where fixed.

In my case it was magento 1.9 and magento 2 (https://github.com/magento/magento2/pull/2124)
