### ISSUE TITLE
Goodreads OAuth Problems

### ISSUE THREAD

**Issue by earthiverse** [googlesamples/apps-script-oauth1#32]
I'm trying to connect my app to Goodreads, but I keep getting an error.

> The state token is invalid or has expired. Please try again.

The callback URL I see in the window with the error has two question marks in it, instead of another ampersand...

`https://script.google.com/macros/d/{Script ID}/usercallback?state={Really Long State String}?oauth_token={Oauth Token}&authorize=1`

edit: I only get the state in the URL if I set `.setOAuthVersion('1.0')`. If I don't set the OAuthVersion, I don't get the state in the callback URL, but I get the same error (state token is invalid or has expired).

Is this something I can fix in a setting on my side with an extra parameter, or is this on Goodreads?

**Comment by stephaniewilkinson** [comment]
Hi! I'm following you over here from goodreads. When you give goodreads the callback URI, it appends` ?oauth_token=token&authorize=1` to the end of the URI. 

Can you get the other params out of your callback?

If not, then maybe there is a way in Oauth to specify that you need an ampersand instead of a question mark. 

Here's how I did it in my app, FWIW: https://github.com/stephaniewilkinson/bookmooch/blob/master/app.rb#L36

**Comment by erickoledadevrel** [comment]
Unfortunately it seems like the Goodreads API isn't following the OAuth 1.0 specification. As per their documentation:

> The oauth_callback param value must not contain any query string params. 

However, the official OAuth 1.0 specification says:

> The callback URL MAY include Consumer provided query parameters. The Service Provider MUST retain them unmodified and append the oauth_token parameter to the existing query.

Apps Script requires a `state` parameter in the `/usercallback` URL in order to run. The library is passing this parameter, but Goodreads is blindly appending it's parameters instead of adding them on with ampersands as required by spec.

**Comment by erickoledadevrel** [comment]
I've been able to work around this bug in their implementation by using the web app URL instead of the normal callback URL, since the web app URL doesn't require any state parameters. I've published [a sample](https://github.com/googlesamples/apps-script-oauth1/blob/master/samples/Goodreads.gs) that shows how to do this.
